
'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Shield, Zap, Eye, Github } from 'lucide-react';
import VideoUploader from '@/components/video-uploader';
import VideoProcessor from '@/components/video-processor';
import ResultsDisplay from '@/components/results-display';
import { VideoFile, VideoAnalysisResult } from '@/lib/types';

export default function Home() {
  const [currentVideo, setCurrentVideo] = useState<VideoFile | string | null>(null);
  const [analysisResult, setAnalysisResult] = useState<VideoAnalysisResult | null>(null);
  const [analysisError, setAnalysisError] = useState<string | null>(null);

  const handleVideoSelect = (video: VideoFile | string) => {
    setCurrentVideo(video);
    setAnalysisResult(null);
    setAnalysisError(null);
  };

  const handleAnalysisResult = (result: VideoAnalysisResult | null) => {
    if (result) {
      setAnalysisResult(result);
      setAnalysisError(null);
    } else {
      setAnalysisResult(null);
      setAnalysisError('Failed to analyze video. Please try again.');
    }
  };

  const handleReset = () => {
    setCurrentVideo(null);
    setAnalysisResult(null);
    setAnalysisError(null);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-purple-900">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-gray-900/80 backdrop-blur-sm border-b border-gray-700">
        <div className="max-w-6xl mx-auto px-6 py-4">
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex items-center justify-between"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 bg-purple-600 rounded-lg">
                <Shield className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white">AI Video Detector</h1>
                <p className="text-gray-400 text-sm">Identify AI-generated video content</p>
              </div>
            </div>
            
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2 text-sm text-gray-400">
                <Eye className="w-4 h-4" />
                <span>92%+ Accuracy</span>
              </div>
              <div className="flex items-center gap-2 text-sm text-gray-400">
                <Zap className="w-4 h-4" />
                <span>Real-time Analysis</span>
              </div>
            </div>
          </motion.div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto px-6 py-8">
        {/* Hero Section */}
        {!currentVideo && !analysisResult && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-12"
          >
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Detect AI-Generated Videos
            </h2>
            <p className="text-xl text-gray-300 mb-8 max-w-3xl mx-auto">
              Upload your video file or paste a URL to analyze whether the content was generated by AI. 
              Our advanced detection system provides accurate results with confidence scores.
            </p>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-4xl mx-auto">
              {[
                {
                  icon: Shield,
                  title: 'Advanced Detection',
                  description: 'Multi-model AI analysis with 92%+ accuracy'
                },
                {
                  icon: Zap,
                  title: 'Fast Processing',
                  description: 'Results in 2-4 minutes with real-time updates'
                },
                {
                  icon: Eye,
                  title: 'Detailed Analysis',
                  description: 'Confidence scores and technical explanations'
                }
              ].map((feature, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 * index }}
                  className="bg-gray-800/50 rounded-lg p-6 border border-gray-700"
                >
                  <feature.icon className="w-8 h-8 text-purple-400 mx-auto mb-3" />
                  <h3 className="text-lg font-semibold text-white mb-2">{feature.title}</h3>
                  <p className="text-gray-400 text-sm">{feature.description}</p>
                </motion.div>
              ))}
            </div>
          </motion.div>
        )}

        {/* Content Sections */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Left Column - Upload/Processing */}
          <div>
            {!currentVideo ? (
              <VideoUploader 
                onVideoSelect={handleVideoSelect}
                disabled={!!currentVideo}
              />
            ) : (
              <VideoProcessor
                video={currentVideo}
                onResult={handleAnalysisResult}
                onReset={handleReset}
              />
            )}
          </div>

          {/* Right Column - Results */}
          <div>
            {(analysisResult || analysisError) && (
              <ResultsDisplay 
                result={analysisResult}
                error={analysisError || undefined}
              />
            )}
          </div>
        </div>

        {/* Information Section */}
        {!currentVideo && !analysisResult && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="mt-16 bg-gray-800/30 rounded-xl p-8 border border-gray-700"
          >
            <h3 className="text-2xl font-bold text-white mb-6 text-center">
              How It Works
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
              {[
                { step: '1', title: 'Upload', desc: 'Upload your video file or provide a URL' },
                { step: '2', title: 'Analyze', desc: 'AI models examine the content for synthetic patterns' },
                { step: '3', title: 'Process', desc: 'Advanced algorithms calculate confidence scores' },
                { step: '4', title: 'Results', desc: 'Get detailed analysis with explanations' }
              ].map((item, index) => (
                <div key={index} className="text-center">
                  <div className="w-12 h-12 bg-purple-600 rounded-full flex items-center justify-center text-white font-bold text-lg mx-auto mb-3">
                    {item.step}
                  </div>
                  <h4 className="text-white font-semibold mb-2">{item.title}</h4>
                  <p className="text-gray-400 text-sm">{item.desc}</p>
                </div>
              ))}
            </div>
          </motion.div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-700 bg-gray-900/50">
        <div className="max-w-6xl mx-auto px-6 py-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="flex items-center gap-3">
              <Shield className="w-5 h-5 text-purple-400" />
              <span className="text-gray-400">AI Video Detector - Identify synthetic content</span>
            </div>
            
            <div className="flex items-center gap-6 text-sm text-gray-500">
              <span>Powered by advanced AI detection models</span>
              <span>•</span>
              <span>Results in 2-4 minutes</span>
              <span>•</span>
              <span>92%+ accuracy rate</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
